export const editorThemes = {
  // Basic themes
  "vs-dark": "VS Dark",
  "vs-light": "VS Light",
  "hc-black": "High Contrast Dark",
  "hc-light": "High Contrast Light",
  
  // Custom themes
  "active4d": "Active4D",
  "all-hallows-eve": "All Hallows Eve",
  "amy": "Amy",
  "birds-of-paradise": "Birds of Paradise",
  "blackboard": "Blackboard",
  "brilliance-black": "Brilliance Black",
  "brilliance-dull": "Brilliance Dull",
  "chrome-devtools": "Chrome DevTools",
  "clouds-midnight": "Clouds Midnight",
  "clouds": "Clouds",
  "cobalt": "Cobalt",
  "dawn": "Dawn",
  "dracula": "Dracula",
  "dreamweaver": "Dreamweaver",
  "eiffel": "Eiffel",
  "espresso-libre": "Espresso Libre",
  "github": "GitHub",
  "idle": "IDLE",
  "katzenmilch": "Katzenmilch",
  "krtheme": "krTheme",
  "kuroir": "Kuroir",
  "lazy": "LAZY",
  "magicwb-amiga": "MagicWB (Amiga)",
  "merbivore-soft": "Merbivore Soft",
  "merbivore": "Merbivore",
  "monokai-bright": "Monokai Bright",
  "monokai": "Monokai",
  "night-owl": "Night Owl",
  "oceanic-next": "Oceanic Next",
  "pastels-on-dark": "Pastels on Dark",
  "slush-and-poppies": "Slush and Poppies",
  "solarized-dark": "Solarized Dark",
  "solarized-light": "Solarized Light",
  "spacecadet": "SpaceCadet",
  "sunburst": "Sunburst",
  "textmate": "TextMate",
  "tomorrow-night-blue": "Tomorrow Night Blue",
  "tomorrow-night-bright": "Tomorrow Night Bright",
  "tomorrow-night-eighties": "Tomorrow Night Eighties",
  "tomorrow-night": "Tomorrow Night",
  "tomorrow": "Tomorrow",
  "twilight": "Twilight",
  "upstream-sunburst": "Upstream Sunburst",
  "vibrant-ink": "Vibrant Ink",
  "xcode": "Xcode",
  "zenburnesque": "Zenburnesque"
}; 